name: download-artifact

description: Download Artifact

inputs:
  platform:
    description: Platform
    required: true
  python_version:
    description: Python version
    required: true

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.platform }}_python-${{ inputs.python_version }}
        path: ${{ inputs.platform }}_python-${{ inputs.python_version }}
    - name: Append path to package_paths.env
      shell: bash
      run: |
        PACKAGE_NAME=$(basename `ls -1 ${{ inputs.platform }}_python-${{ inputs.python_version }}/*.whl`)
        mv ${{ inputs.platform }}_python-${{ inputs.python_version }}/*.whl ./
        echo "$PACKAGE_NAME" >> package_paths.env
