name: "Slack Notify Succeeded"

description: "Send a Slack notification for succeeded jobs"

runs:
  using: "composite"
  steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: sora-python-sdk
        SLACK_COLOR: good
        SLACK_TITLE: SUCCEEDED
        SLACK_ICON_EMOJI: ":star-struck:"
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
