name: build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
      - "tests/**"
      - ".github/workflows/e2e-test.yml"
    branches-ignore:
      - "feature/e2e-test*"
    tags:
      - "*"
  schedule:
    # UTC の 01:00 は JST だと 10:00 。
    # 1-5 で 月曜日から金曜日
    - cron: "0 1 * * 1-5"

permissions:
  contents: write
  actions: read

jobs:
  # VERSION ファイルからバージョン情報を取得
  get_sdk_version:
    runs-on: ubuntu-slim
    outputs:
      sdk_version: ${{ steps.version.outputs.sdk_version }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          sparse-checkout: |
            VERSION
          sparse-checkout-cone-mode: false
      - id: version
        run: |
          SDK_VERSION=$(cat VERSION)
          echo "sdk_version=$SDK_VERSION" >> $GITHUB_OUTPUT
          echo "SDK Version: $SDK_VERSION"

  build_ubuntu:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: ubuntu-24.04_x86_64
            runs_on: ubuntu-24.04
        python_version:
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: ${{ matrix.platform.runs_on }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: |
          sudo apt-get update
          sudo apt-get -y install libx11-dev
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: false
          python-version: ${{ matrix.python_version }}
      - run: uv sync --no-install-project
      - run: uv build --wheel
      - run: uv pip install dist/*.whl
      - run: uv run --no-sync pytest tests/test_version.py
      - name: Upload Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.platform.name }}_python-${{ matrix.python_version }}
          path: "dist/"

  slack_notify:
    needs: [build_ubuntu]
    runs-on: ubuntu-slim
    if: ${{ !cancelled() }}
    steps:
      - name: Slack Notification
        uses: shiguredo/github-actions/.github/actions/slack-notify@main # main
        with:
          status: ${{ job.status }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_channel: sora-python-sdk
          notify_mode: failure_and_fixed
        env:
          GH_TOKEN: ${{ github.token }}
