name: examples-e2e-test

on:
  push:
    paths-ignore:
      - "**.md"
  schedule:
    # UTC の 01:00 は JST だと 10:00 。
    # 1-5 で 月曜日から金曜日
    - cron: "0 1 * * 1-5"

env:
  TEST_SIGNALING_URLS: ${{ secrets.TEST_SIGNALING_URLS }}
  TEST_CHANNEL_ID_PREFIX: ${{ secrets.TEST_CHANNEL_ID_PREFIX }}
  TEST_SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}

jobs:
  e2e_ubuntu_test:
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
        os: ["ubuntu-22.04", "ubuntu-24.04"]
        sdk: ["source", "pkg"]
    runs-on: ${{ matrix.os}}
    defaults:
      run:
        working-directory: ./examples
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      # libx11-dev は Ubuntu 24.04 の時に必要になる模様
      - run: |
          sudo apt-get update
          sudo apt-get -y install libva2 libdrm2 libva-dev libdrm-dev libx11-dev portaudio19-dev
      - name: Download openh264
        run: |
          curl -LO http://ciscobinary.openh264.org/libopenh264-2.4.1-linux64.7.so.bz2
          bzip2 -d libopenh264-2.4.1-linux64.7.so.bz2
          mv libopenh264-2.4.1-linux64.7.so libopenh264.so
          echo "OPENH264_PATH=$(pwd)/libopenh264.so" >> $GITHUB_ENV
      - uses: eifinger/setup-rye@v4
      - if: ${{ matrix.sdk == 'source'}}
        run: |
          echo '[tool.rye.workspace]' >> pyproject.toml
          echo 'packages = ["examples"]' >> pyproject.toml
        working-directory: .
      - if: ${{ matrix.sdk == 'source'}}
        run: rye sync
        working-directory: .
      - if: ${{ matrix.sdk == 'source'}}
        run: rye run python3 run.py ${{ matrix.os }}_x86_64
        working-directory: .
      - run: rye pin ${{ matrix.python_version }}
      - run: rye sync
      - run: rye run pytest tests/test_openh264.py -s
      - run: rye run pytest tests/test_messaging.py -s
      - run: rye run pytest tests/test_sendonly_recvonly.py -s
      - run: rye run pytest tests/test_vad.py -s

  e2e_macos_test:
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
        # macos-13 は test_macos.py が上手くテストが動かないのでスキップ
        os: ["macos-14"]
        sdk: ["source", "pkg"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./examples
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Download openh264
        run: |
          curl -LO http://ciscobinary.openh264.org/libopenh264-2.4.1-mac-arm64.dylib.bz2
          bzip2 -d libopenh264-2.4.1-mac-arm64.dylib.bz2
          mv libopenh264-2.4.1-mac-arm64.dylib libopenh264.dylib
          echo "OPENH264_PATH=$(pwd)/libopenh264.dylib" >> $GITHUB_ENV
      - uses: eifinger/setup-rye@v4
      - if: ${{ matrix.sdk == 'source'}}
        run: |
          echo '[tool.rye.workspace]' >> pyproject.toml
          echo 'packages = ["examples"]' >> pyproject.toml
        working-directory: .
      - if: ${{ matrix.sdk == 'source'}}
        run: rye sync
        working-directory: .
      - if: ${{ matrix.sdk == 'source'}}
        run: rye run python3 run.py macos_arm64
        working-directory: .
      - run: rye pin ${{ matrix.python_version }}
      - run: rye sync
      - run: rye run pytest tests/test_macos.py -s
      - run: rye run pytest tests/test_openh264.py -s
      - run: rye run pytest tests/test_messaging.py -s
      - run: rye run pytest tests/test_sendonly_recvonly.py -s
      - run: rye run pytest tests/test_vad.py -s

  e2e_windows_test:
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
        sdk: ["source", "pkg"]
    runs-on: windows-2022
    defaults:
      run:
        working-directory: ./examples
    timeout-minutes: 20
    env:
      # Python を強制的に UTF-8 で利用するおまじない
      PYTHONUTF8: 1
    steps:
      - uses: actions/checkout@v4
      - name: Download openh264
        shell: pwsh
        run: |
          $url = "http://ciscobinary.openh264.org/openh264-2.4.1-win64.dll.bz2"
          Invoke-WebRequest -Uri $url -OutFile "openh264-2.4.1-win64.dll.bz2"
          7z e openh264-2.4.1-win64.dll.bz2
          Rename-Item -Path "openh264-2.4.1-win64.dll" -NewName "libopenh264.dll"
          echo "OPENH264_PATH=$PWD\libopenh264.dll" >> $env:GITHUB_ENV
      - uses: eifinger/setup-rye@v4
      - if: ${{ matrix.sdk == 'source'}}
        run: |
          echo '[tool.rye.workspace]' >> pyproject.toml
          echo 'packages = ["examples"]' >> pyproject.toml
        working-directory: .
      - if: ${{ matrix.sdk == 'source'}}
        run: rye sync
        working-directory: .
      - if: ${{ matrix.sdk == 'source'}}
        run: rye run python run.py windows_x86_64
        working-directory: .
      - run: rye pin ${{ matrix.python_version }}
      - run: rye sync
      - run: rye run pytest tests/test_messaging.py -s
      - run: rye run pytest tests/test_sendonly_recvonly.py -s
      - run: rye run pytest tests/test_vad.py -s

  slack_notify_succeeded:
    needs: [e2e_ubuntu_test, e2e_macos_test, e2e_windows_test]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: sora-python-sdk
          SLACK_COLOR: good
          SLACK_TITLE: SUCCEEDED
          SLACK_ICON_EMOJI: ":star-struck:"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  slack_notify_failed:
    needs: [e2e_ubuntu_test, e2e_macos_test, e2e_windows_test]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: sora-python-sdk
          SLACK_COLOR: danger
          SLACK_TITLE: "FAILED"
          SLACK_ICON_EMOJI: ":japanese_ogre:"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}  